# - debug:
#     msg : Hello

# Following steps need to be run manually
# sudo curl -L -o /etc/yum.repos.d/gh-cli.repo https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install gh -y
# gh auth login -s admin:org


- name: Setup Prompt
  ansible.builtin.shell: set-prompt github-runner

- name: Create github directory
  ansible.builtin.file:
      path: /actions-runner
      state: directory

- name: Download and extract runner
  ansible.builtin.unarchive:
      src: https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-x64-2.321.0.tar.gz
      dest: "/actions-runner"
      remote_src: yes

- name: Grab Token
  ansible.builtin.shell: |
    gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/Shefali-DevOps/actions/runners/registration-token | jq .token
  register: out

- name: Print Token
  ansible.builtin.debug:
    msg: "{{ out }}"
